package com.example.pojo;

import javax.persistence.*;

@Table(name = "person")
public class Person extends BaseEntity{


    @Id
    @Column(name = "p_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Transient
    private Integer startAge;
    @Transient
    private Integer endAge;

    public Integer getStartAge() {
        return startAge;
    }

    public void setStartAge(Integer startAge) {
        this.startAge = startAge;
    }

    public Integer getEndAge() {
        return endAge;
    }

    public void setEndAge(Integer endAge) {
        this.endAge = endAge;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.p_age
     *
     * @mbggenerated
     */
    private Integer pAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_id
     *
     * @return the value of person.p_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_id
     *
     * @param id the value for person.p_id
     *
     * @mbggenerated
     */
    public void setpId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_name
     *
     * @return the value of person.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_name
     *
     * @param pName the value for person.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_age
     *
     * @return the value of person.p_age
     *
     * @mbggenerated
     */
    public Integer getpAge() {
        return pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_age
     *
     * @param pAge the value for person.p_age
     *
     * @mbggenerated
     */
    public void setpAge(Integer pAge) {
        this.pAge = pAge;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + getId() +
                ", pName='" + pName + '\'' +
                ", pAge=" + pAge +
                '}';
    }
}