package com.example.mapper.ds2;

import com.example.pojo.Person;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component("personMapper2")
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Delete({
        "delete from person",
        "where p_id = #{pId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Insert({
        "insert into person (p_id, p_name, ",
        "p_age)",
        "values (#{pId,jdbcType=INTEGER}, #{pName,jdbcType=VARCHAR}, ",
        "#{pAge,jdbcType=INTEGER})"
    })
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @InsertProvider(type=PersonSqlProvider.class, method="insertSelective")
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "p_id, p_name, p_age",
        "from person",
        "where p_id = #{pId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="p_id", property="pId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="p_name", property="pName", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_age", property="pAge", jdbcType=JdbcType.INTEGER)
    })
    Person selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @UpdateProvider(type=PersonSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Update({
        "update person",
        "set p_name = #{pName,jdbcType=VARCHAR},",
          "p_age = #{pAge,jdbcType=INTEGER}",
        "where p_id = #{pId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Person record);
}