package com.example.pojo;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.p_age
     *
     * @mbggenerated
     */
    private Integer pAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_id
     *
     * @return the value of person.p_id
     *
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_id
     *
     * @param pId the value for person.p_id
     *
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_name
     *
     * @return the value of person.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_name
     *
     * @param pName the value for person.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.p_age
     *
     * @return the value of person.p_age
     *
     * @mbggenerated
     */
    public Integer getpAge() {
        return pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.p_age
     *
     * @param pAge the value for person.p_age
     *
     * @mbggenerated
     */
    public void setpAge(Integer pAge) {
        this.pAge = pAge;
    }


    @Override
    public String toString() {
        return "Person{" +
                "pId=" + pId +
                ", pName='" + pName + '\'' +
                ", pAge=" + pAge +
                '}';
    }
}